name = "prompt-studio"
main = ".open-next/worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"

[[durable_objects.bindings]]
name = "DOQueueHandler"
class_name = "DOQueueHandler"

[[durable_objects.bindings]]
name = "DOShardedTagCache"
class_name = "DOShardedTagCache"

[[durable_objects.bindings]]
name = "BucketCachePurge"
class_name = "BucketCachePurge"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["DOQueueHandler", "DOShardedTagCache", "BucketCachePurge"]
